ejemplo1/proyectoUno/administrativo/urls.py
"""
    Manejo de urls para la aplicación
    administrativo
"""
from django.urls import path
# se importa las vistas de la aplicación
from . import views


urlpatterns = [
        path('', views.index, name='index'),
        path('estudiante/<int:id>', views.obtener_estudiante, 
            name='obtener_estudiante'),
        path('crear/estudiante', views.crear_estudiante, 
            name='crear_estudiante'),
        path('editar_estudiante/<int:id>', views.editar_estudiante, 
            name='editar_estudiante'),
        path('eliminar/estudiante/<int:id>', views.eliminar_estudiante, 
            name='eliminar_estudiante'),
        # numeros telefonicos
        path('crear/numero/telefonico', views.crear_numero_telefonico, 
            name='crear_numero_telefonico'),
        path('editar/numero/telefonico/<int:id>', views.editar_numero_telefonico, 
            name='editar_numero_telefonico'),
        path('crear/numero/telefonico/estudiante/<int:id>', 
            views.crear_numero_telefonico_estudiante, 
            name='crear_numero_telefonico_estudiante'),
 ]

ejemplo1/proyectoUno/proyectoUno/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrativo.urls')),
]

ejemplo1/proyectoUno/administrativo/models.py
from django.db import models

# Create your models here.

class Estudiante(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    cedula = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return "%s %s %s" % (self.nombre, 
                self.apellido,
                self.cedula)

class NumeroTelefonico(models.Model):
    telefono = models.CharField(max_length=100)
    tipo = models.CharField(max_length=100)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE,
            related_name="numeros_telefonicos")

    def __str__(self):
        return "%s %s" % (self.telefono, self.tipo)

ejemplo1/proyectoUno/administrativo/forms.py
from django.forms import ModelForm
from django import forms

from administrativo.models import Estudiante, \
        NumeroTelefonico


class EstudianteForm(ModelForm):
    class Meta:
        model = Estudiante
        fields = ['nombre', 'apellido', 'cedula']


class NumeroTelefonicoForm(ModelForm):
    class Meta:
        model = NumeroTelefonico
        fields = ['telefono', 'tipo', 'estudiante']


class NumeroTelefonicoEstudianteForm(ModelForm):

    def __init__(self, estudiante, *args, **kwargs):
        super(NumeroTelefonicoEstudianteForm, self).__init__(*args, **kwargs)
        self.initial['estudiante'] = estudiante
        self.fields["estudiante"].widget = forms.widgets.HiddenInput()
        print(estudiante)

    class Meta:
        model = NumeroTelefonico
        fields = ['telefono', 'tipo', 'estudiante']

ejemplo1/proyectoUno/administrativo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render

# importar las clases de models.py
from administrativo.models import *

# importar los formularios de forms.py
from administrativo.forms import *

# Create your views here.

def index(request):
    """
        Listar los registros del modelo Estudiante,
        obtenidos de la base de datos.
    """
    # a través del ORM de django se obtiene
    # los registros de la entidad; el listado obtenido
    # se lo almacena en una variable llamada
    # estudiantes
    estudiantes = Estudiante.objects.all()
    # en la variable tipo diccionario llamada informacion_template
    # se agregará la información que estará disponible
    # en el template
    informacion_template = {'estudiantes': estudiantes, 'numero_estudiantes': len(estudiantes)}
    return render(request, 'index.html', informacion_template)


def obtener_estudiante(request, id):
    """
        Listar los registros del modelo Estudiante,
        obtenidos de la base de datos.
    """
    # a través del ORM de django se obtiene
    # los registros de la entidad; el listado obtenido
    # se lo almacena en una variable llamada
    # estudiantes
    estudiante = Estudiante.objects.get(pk=id)
    # en la variable tipo diccionario llamada informacion_template
    # se agregará la información que estará disponible
    # en el template
    informacion_template = {'estudiante': estudiante}
    return render(request, 'obtener_estudiante.html', informacion_template)


def crear_estudiante(request):
    """
    """
    if request.method=='POST':
        formulario = EstudianteForm(request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save() # se guarda en la base de datos
            return redirect(index)
    else:
        formulario = EstudianteForm()
    diccionario = {'formulario': formulario}

    return render(request, 'crearEstudiante.html', diccionario)


def editar_estudiante(request, id):
    """
    """
    estudiante = Estudiante.objects.get(pk=id)
    if request.method=='POST':
        formulario = EstudianteForm(request.POST, instance=estudiante)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = EstudianteForm(instance=estudiante)
    diccionario = {'formulario': formulario}

    return render(request, 'editarEstudiante.html', diccionario)


def eliminar_estudiante(request, id):
    """
    """
    estudiante = Estudiante.objects.get(pk=id)
    estudiante.delete()
    return redirect(index)


def crear_numero_telefonico(request):
    """
    """

    if request.method=='POST':
        formulario = NumeroTelefonicoForm(request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = NumeroTelefonicoForm()
    diccionario = {'formulario': formulario}

    return render(request, 'crearNumeroTelefonico.html', diccionario)


def editar_numero_telefonico(request, id):
    """
    """
    telefono = NumeroTelefonico.objects.get(pk=id)
    if request.method=='POST':
        formulario = NumeroTelefonicoForm(request.POST, instance=telefono)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = NumeroTelefonicoForm(instance=telefono)
    diccionario = {'formulario': formulario}

    return render(request, 'crearNumeroTelefonico.html', diccionario)

def crear_numero_telefonico_estudiante(request, id):
    """
    """
    estudiante = Estudiante.objects.get(pk=id)
    if request.method=='POST':
        formulario = NumeroTelefonicoEstudianteForm(estudiante, request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = NumeroTelefonicoEstudianteForm(estudiante)
    diccionario = {'formulario': formulario, 'estudiante': estudiante}

    return render(request, 'crearNumeroTelefonicoEstudiante.html', diccionario)

ejemplo1/proyectoUno/administrativo/templates/crearEstudiante.html
{% extends "master.html" %}

{% block content %}
<h2>Crear Estudiante</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Agregar'/></p>
</form>

[<a href="{% url 'index' %}">inicio</a>]
{% endblock %}

ejemplo1/proyectoUno/administrativo/templates/crearNumeroTelefonico.html
<h2>Crear Número Telefónico</h3>

<form action="" method="post">

  {% csrf_token %}

  {{formulario.as_p}}

  <p><input type='submit' value='Agregar'/></p>
</form>

[<a href="{% url 'index' %}">inicio</a>]

ejemplo1/proyectoUno/administrativo/templates/crearNumeroTelefonicoEstudiante.html
<h2>Crear Número Telefónico para {{estudiante}}</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Agregar'/></p>
</form>

[<a href="{% url 'index' %}">inicio</a>]

ejemplo1/proyectoUno/administrativo/templates/editarEstudiante.html
<h2>Editar Estudiante</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Actualizar'/></p>
</form>

[<a href="{% url 'index' %}">inicio</a>]

ejemplo1/proyectoUno/administrativo/templates/index.html
{% extends "master.html" %}

{% block title %}
  Listado de Estudiantes
{% endblock %}

{% block content %}
<h3>Número de estudiantes {{ numero_estudiantes }}</h3>

<ul>
 {% for e in estudiantes %}

  <li>
    {{e}} - [<a href="{% url 'obtener_estudiante' e.id %}">ver</a>] -
    [<a href="{% url 'editar_estudiante' e.id %}">editar</a>] -
    [<a href="{% url 'eliminar_estudiante' e.id %}"
      onclick="return confirm('¿Está seguro de la eliminación?')" >
      eliminar</a>]
      <ul>
        {% for t in e.numeros_telefonicos.all %}
          <li>
            <span>{{t.telefono}} - {{t.tipo}} - [<a href="{% url 'editar_numero_telefonico' t.id %}">editar</a>] </span>
          </li>
        {% endfor %}
      </ul>
    [<a href="{% url 'crear_numero_telefonico_estudiante' e.id%}">+Teléfono</a>]
  </li>
  <hr />

{% endfor %}
</ul>

<br />
[<a href="{% url 'crear_estudiante' %}">agregar estudiante</a>]

<br />
[<a href="{% url 'crear_numero_telefonico' %}">agregar telefono</a>]

{% endblock %}

ejemplo1/proyectoUno/administrativo/templates/listadoEstudiantesDos.html
<h2>Listado de Estudiantes</h3>
<h3>Número de estudiantes {{ numero_estudiantes }}</h3>

{% for e in estudiantes %}
    
  {{e}}<br/>
  <ul>
  {% for numero in e.numerotelefonico_set.all%}
      <li>
          Número telefónico {{numero}}<br/>
      </li>
  {% endfor %}
  </ul>
  <br/>
{% endfor %}

ejemplo1/proyectoUno/administrativo/templates/master.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>
    <h1>Aplicación Administración </h1>
    <hr>
      {% block content %}
      {% endblock %}

    <hr>
    <footer>
      <p>Loja-Ecuador</p>
      <p>{% now "j F Y H:i" %}</p>
    </footer>
  </body>
</html>

ejemplo1/proyectoUno/administrativo/templates/obtener_estudiante.html
<h3>Datos de estudiante</h3>

<p><b>Nombre:</b>{{estudiante.nombre}}</p>
<p><b>Apellido:</b>{{estudiante.apellido}}</p>
<p><b>Cédula:</b>{{estudiante.cedula}}</p>

<br/>
[<a href="{% url 'index' %}">inicio</a>]